### ISSUE TITLE
Some skills aren't tracking in casts.

### ISSUE THREAD

**Issue by DanteMccloud** [Zerthox/arcdps-buddy#13]
Not tracking Reaper dagger or sword skill casts.

![image](https://github.com/Zerthox/arcdps-buddy/assets/20995515/e520828c-49c6-4491-b44b-b061eb6c3cd4)

**Comment by Zerthox** [comment]
Buddy only displays casts for skills that have been added to the default skill definitions or are in the user's custom skill definition file.

**Comment by DanteMccloud** [comment]
> Buddy only displays casts for skills that have been added to the default skill definitions or are in the user's custom skill definition file.

ah ok, is that the yml files in the src/skills folder? I'll see about adding some and dropping a PR ^.^

**Comment by Zerthox** [comment]
Correct, those are the default skills the plugin ships with. The format as well as how to add custom skills is [documented in the readme](https://github.com/Zerthox/arcdps-buddy?tab=readme-ov-file#casts). Feel free to PR or suggest default skills that you think most people would find useful.
